### ISSUE TITLE
RangeError: Maximum call stack size exceeded with custom validator

### ISSUE THREAD

**Issue by dgcoffman** [christianalfoni/formsy-react#298] opened 2016-01-13 22:49 UTC
`"react": "0.14.2",`
`"formsy-react": "0.17.0",`

We have a component `Form`:
```javascript
import Formsy from 'lib/Formsy';
import FormInput from 'FormInput.jsx';
import React from 'react';

const Form = React.createClass({
  render()
  {
    return (
      <div>
        <Formsy.Form onValid={() =>  this.setState({anything: true})}>
          <FormInput name="uid" validations={{ customValidator: () => true }} />
        </Formsy.Form>
      </div>
    );
  },
});
export default Form;
```

using `FormInput`:
```javascript
const React = require('React');
const Formsy = require('lib/Formsy');

const FormInput = React.createClass({
  mixins: [Formsy.Mixin],

  changeValue: function (event) {
    this.setValue(event.currentTarget.value);
  },

  render() {
    return <input type="text" onChange={this.changeValue}/>
  },
});

module.exports = FormInput;
```

Mounting the component or typing a character in the input causes `RangeError: Maximum call stack size exceeded` to be thrown to the console. 

FWIW, here is a screenshot of the stacktrace for the exception thrown on component mount:
![stack trace](http://i.imgur.com/OfMNcWq.png)

Replacing `customValidator: () => true` with a built-in validator like `isExisty: true` does not cause this exception to be thrown. 

Registering a custom validator like:
```javascript
Formsy.addValidationRule('isAnything', function(values, value, array) {
  return true;
});
```
and then using it
```javascript
isAnything: true
```
does not cause this exception to be thrown. 

I haven't been able to figure out how to implement a custom validator as shown in this example: https://github.com/christianalfoni/formsy-react/blob/master/API.md#validations

Similar issue: https://github.com/christianalfoni/formsy-react/issues/106

**Comment by tnrich** [comment] 2016-01-27 06:40
I am also seeing this error. Either this should get fixed, or the "inline" custom validator examples should be removed

**Comment by te-chris** [comment] 2016-02-02 14:11
I'm seeing this as well.  I've created a custom component and it's causing an infinite loop when there is no validation set.  When I set validations to `isExisty` it behaves as expected.

**Comment by jwohlfert23** [comment] 2016-03-10 18:18
+1

**Comment by jamedranoa** [comment] 2016-03-15 21:00
the problem is coming from [here](https://github.com/christianalfoni/formsy-react/blob/master/src/Mixin.js#L99), that `if` condition will always be `false` if the component has a custom validation (a function) because  the function [isSame](https://github.com/christianalfoni/formsy-react/blob/master/src/utils.js#L39) will always return false when is comparing the two functions allocated in two different objects (new props, prevProps). and the function `formsy.validate` will make use of `setState` which will repeat the cycle.

one solution (not ideal) could be adding a condition to compare functions on the isSame function and compare the `toString` result. 

```javascript
 fun1.toString() === fun2.toString();
```

but I'm not sure if this could have negative implications in others parts of the code.

**Comment by megapctr** [comment] 2016-03-21 09:58
@jamedranoa fantastic job debugging this!

**Comment by megapctr** [comment] 2016-03-21 10:03
Other way you can get custom validators is this

```js
Formsy.addValidationRule('notIn', (values, value, array) => !_.includes(array, value))

// usage
validations: {
    matchRegexp: /^[\w -]+$/,
    notIn: reservedNames,
},
```

**Comment by stupidisum** [comment] 2016-05-09 06:48
Why is this not fixed yet?

**Comment by dgcoffman** [comment] 2016-05-09 19:25
I think removing it from the docs and marking wontfix would be sufficient, if maintainers have no interest in fixing this feature.

**Comment by cj3kim** [comment] 2016-05-20 00:56
+1

**Comment by cj3kim** [comment] 2016-05-20 20:30
When will the solution be merged in?

**Closed** 2016-07-05 08:36 UTC
